Run `dstack-proxy` on gateways (#2136)
- Import the proxy FastAPI app from dstack to
  dstack-gateway.
- Remove the now-unused code in dstack-gateway.
  The package itself will remain for now, since it
  still contains the installation logic. The
  package may be discarded later.
- Update GitHub Actions to pin the dstack
  dependency version in dstack-gateway for release
  builds.
- Update dstack server to accommodate for the API
  differences between dstack-gateway and
  dstack-proxy.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -163,6 +163,11 @@ jobs:
       - name: Build package
         run: |
           echo "__version__ = \"${{ env.VERSION }}\"" > src/dstack/gateway/version.py
+          sed \
+            -i.old \
+            "s|@ https://github.com/dstackai/dstack/archive/refs/heads/master.zip|== ${{ env.VERSION }}|" \
+            pyproject.toml
+          diff pyproject.toml pyproject.toml.old > /dev/null && echo "Could not set version" && exit 1
           python -m build .
       - name: Upload to S3
         env:
